name: libero360
description: "Libero360 - Aplicación de gestión de voleibol con estadísticas en tiempo real"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.6

  # Base de datos local - Isar
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  
  # Para obtener el directorio de la app
  path_provider: ^2.1.2
  
  # Gestión de estado (opcional pero recomendado para MVVM)
  provider: ^6.1.1
  
  # Gráficos
  fl_chart: ^0.66.2
  
  # Utilidades
  intl: ^0.19.0
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  
  # Generador de código Isar
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true

  assets:
    - assets/images/
