// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWBreTjiE6gaO0zL5dhWINc5cbOhwntm0',
    appId: '1:184026715526:web:59e9e77186759e51744807',
    messagingSenderId: '184026715526',
    projectId: 'libero360-8409b',
    authDomain: 'libero360-8409b.firebaseapp.com',
    storageBucket: 'libero360-8409b.firebasestorage.app',
    measurementId: 'G-9XP5QE8KMR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVGpLdTZkB7inYDJmcQFz_ZmwV7lyLLlo',
    appId: '1:184026715526:android:5c481447dc0b3113744807',
    messagingSenderId: '184026715526',
    projectId: 'libero360-8409b',
    storageBucket: 'libero360-8409b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjM-v91KKsQgFMfXN0rjTAbI4ghMJGo-A',
    appId: '1:184026715526:ios:c033893b6f84a1cf744807',
    messagingSenderId: '184026715526',
    projectId: 'libero360-8409b',
    storageBucket: 'libero360-8409b.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjM-v91KKsQgFMfXN0rjTAbI4ghMJGo-A',
    appId: '1:184026715526:ios:c033893b6f84a1cf744807',
    messagingSenderId: '184026715526',
    projectId: 'libero360-8409b',
    storageBucket: 'libero360-8409b.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWBreTjiE6gaO0zL5dhWINc5cbOhwntm0',
    appId: '1:184026715526:web:4604d1d91e1292c8744807',
    messagingSenderId: '184026715526',
    projectId: 'libero360-8409b',
    authDomain: 'libero360-8409b.firebaseapp.com',
    storageBucket: 'libero360-8409b.firebasestorage.app',
    measurementId: 'G-Q8D4KZENEK',
  );
}
